# Day-2
## Functions

In [1]:
def demo():
    """
    Function for demo purpose
    
    Parameters
    ----------
    None
    Return
    ---------
    None
    
    """
    pass

In [4]:
## Get description of function
help(demo)

Help on function demo in module __main__:

demo()
    Function for demo purpose
    
    Parameters
    ----------
    None
    Return
    ---------
    None



In [11]:
def sqr(x: int) -> int:
    """
    Function to squaare an integer number
    
    Parameters:
    -----------
    x integer value
    
    Return:
    ----------
    x*x square of x
    """
    
    return x*x

def callie(fun: 'function', x: int) -> int:
    """
    Function to demonstarate the function as arguement
    
    Parameters:
    -----------
    fun function
    x integer value
    
    Returns:
    ---------
    fun(x)
    
    """
    return fun(x)

In [12]:
callie(sqr, 3)

9

In [8]:
print(type(demo))

<class 'function'>


In [16]:
## default functions

pi = 3.141592653589793238

## round the decimal part with positive number
print(round(pi, ndigits=3))
print(round(pi, ndigits=2))
print(round(pi, ndigits=0))

3.142
3.14
3.0


In [24]:
## rounds the non decimal point tens and hundreds and thousands place with negetive number
## tens : -1
## hundreds place : -2
## thousands place : -3

x = 68378246723.7984732893
print(f"Tens : {round(x, ndigits=-1)}")
print(f"hundreds : {round(x, ndigits=-2)}")
print(f"Thousands : {round(x, ndigits=-3)}")
print(f"all : {round(x, ndigits=-12)}")

Tens : 68378246720.0
hundreds : 68378246700.0
Thousands : 68378247000.0
all : 0.0


In [27]:
#Absalute value
print(f"abs(-3) : {abs(-3)}")
print(f"abs(-0) : {abs(-0)}")
print(f"abs(23) : {abs(23)}")

abs(-3) : 3
abs(-0) : 0
abs(23) : 23


In [29]:
## max & min funciton
print(f"max(34, 56) : {max(34, 56)}")
print(f"min(34, 56) : {min(34, 56)}")

max(34, 56) : 56
min(34, 56) : 34


# Day - 3
## Boolean

In [30]:
x = True
print(x)
print(type(x))

True
<class 'bool'>


##### Comparison oparator

| oparation | Description | oparation | Description |
|-----------|-------------|-----------|-------------|
| a == b | a equal to b | a != b | a not equal to b |
| a > b | a greater than b | a < b | a less than b |



In [32]:
def compare(a, b):
    return a >= b

compare(2,5)

False

In [40]:
## oparations
print(f"True and False = {True and False}")
print(f"True or False = {True or False}")
print(f"True and True = {True and True}")
print(f"False and False = {False and False}")
print(f"True or True = {True or True}")
print(f"Fale or False = {False or False}")
print(f" not True  = {not True}")

True and False = False
True or False = True
True and True = True
False and False = False
True or True = True
Fale or False = False
 not True  = False


In [41]:
True or False and True

True

In [45]:
print(bool(""))
print(bool("asd"))
print(bool(1))
print(bool(0))

False
True
True
False


# Day - 4
## Lists

In [46]:
primes = [2, 3, 5]

In [54]:
## indexing
## Forward 0 to len(arr)
## reversindexign -1 to -len(arr)
print(f"{primes[-len(primes)]}, {primes[1]}")

2, 3


In [56]:
## Slicing
## 0, 1
primes[:2]

[2, 3]

In [58]:
## 0, to end
primes[:]

[2, 3, 5]

In [60]:
## untill last [0, len(arr))
primes[:-1]

[2, 3]

In [102]:
# list are mutabe can be changed
players = ["Messi", "Christiano ronoldo", "Ronaldino", "Naymer", "Mbappe", "Milka Singh"]

In [103]:
players[-1] = "Sunil"

In [104]:
players

['Messi', 'Christiano ronoldo', 'Ronaldino', 'Naymer', 'Mbappe', 'Sunil']

In [106]:
## list functions
## adding elements
players.append("Pogba")
players.append("zlatan")

In [107]:
players

['Messi',
 'Christiano ronoldo',
 'Ronaldino',
 'Naymer',
 'Mbappe',
 'Sunil',
 'Pogba',
 'Pogba',
 'zlatan']

In [108]:
len(players)

9

In [82]:
sum(primes)

10

In [135]:
_dummy = primes[:]
print(_dummy)
_dummy.sort(reverse=True)
print(_dummy)

[2, 3, 5]
[5, 3, 2]


In [83]:
max(primes)

5

In [84]:
min(primes)

2

In [94]:
## every number object in python has a imaginary part
## let
x = 3
type(x)

int

In [95]:
## for integer imaginary will be 0
x.imag

0

In [96]:
y = 10 + 3j

In [97]:
type(y)

complex

In [98]:
y.imag

3.0

In [100]:
x.bit_length

<function int.bit_length()>

In [101]:
x.bit_length()

2

In [109]:
## delete last element
players.pop()

'zlatan'

In [111]:
players.index('Messi')

0

In [112]:
players.index('zlatan')

ValueError: 'zlatan' is not in list

In [113]:
'Naymer' in players

True

In [114]:
'zlatan' in players

False

In [115]:
## get all the associated methods
help(players)

Help on list object:

class list(object)
 |  list(iterable=(), /)
 |  
 |  Built-in mutable sequence.
 |  
 |  If no argument is given, the constructor creates a new empty list.
 |  The argument must be an iterable if specified.
 |  
 |  Methods defined here:
 |  
 |  __add__(self, value, /)
 |      Return self+value.
 |  
 |  __contains__(self, key, /)
 |      Return key in self.
 |  
 |  __delitem__(self, key, /)
 |      Delete self[key].
 |  
 |  __eq__(self, value, /)
 |      Return self==value.
 |  
 |  __ge__(self, value, /)
 |      Return self>=value.
 |  
 |  __getattribute__(self, name, /)
 |      Return getattr(self, name).
 |  
 |  __getitem__(...)
 |      x.__getitem__(y) <==> x[y]
 |  
 |  __gt__(self, value, /)
 |      Return self>value.
 |  
 |  __iadd__(self, value, /)
 |      Implement self+=value.
 |  
 |  __imul__(self, value, /)
 |      Implement self*=value.
 |  
 |  __init__(self, /, *args, **kwargs)
 |      Initialize self.  See help(type(self)) for accurate sign

## Tuples

In [118]:
## defined in ()
## are immutable means value cannot be changed once set
## less memory consumption than list since it is not stored as array
t1 = (1,2,3)

In [121]:
print(f"t1 : {t1}\n")
print(f"typw(t1) : {type(t1)}")

t1 : (1, 2, 3)

typw(t1) : <class 'tuple'>


In [123]:
x = 3.142

In [124]:
x.as_integer_ratio()

(7075155014599049, 2251799813685248)

In [125]:
x = 0.5
x.as_integer_ratio()

(1, 2)

In [126]:
num, den = x.as_integer_ratio()

In [127]:
num/den

0.5

In [130]:
help(x.conjugate)

Help on built-in function conjugate:

conjugate() method of builtins.float instance
    Return self, the complex conjugate of any float.



In [131]:
## swapping using two variable
a = 10
b = 54
a, b = b, a

In [132]:
print(a, b)

54 10


In [136]:
arrivals=['Adela', 'Fleda', 'Owen', 'May', 'Mona', 'Gilbert', 'Ford']

In [139]:
x = len(arrivals)//2 + 1 

In [140]:
arrivals.index('Ford')

6

In [141]:
6 > x

True

# Day - 5
## Loops and lists 


In [142]:
planets = ['Mercury', 'Venus', 'Earth', 'Mars', 'Jupiter', 'Saturn', 'Uranus', 'Neptune']
for planet in planets:
    print(planet, end=' ')

Mercury Venus Earth Mars Jupiter Saturn Uranus Neptune 

In [144]:
multiplicands = (2, 2, 2, 3, 3, 5)
product = 5
for mult in multiplicands:
    product *= mult
product

1800

###### List Comprehension
> List comprehensions are one of Python's most beloved and unique features. The easiest way to understand them is probably to just look at a few examples:

In [148]:
squares = [i**2 for i in range(1, 11)]
squares

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]

In [149]:
[
    planet.upper() + '!' 
    for planet in planets 
    if len(planet) < 6
]

['VENUS!', 'EARTH!', 'MARS!']

# Day - 6
### String and dictionaries

# Day - 7
## imports

In [2]:
import math

print(type(math))

<class 'module'>


- module is a collection of variables or namespaces

In [3]:
print(dir(math))

['__doc__', '__file__', '__loader__', '__name__', '__package__', '__spec__', 'acos', 'acosh', 'asin', 'asinh', 'atan', 'atan2', 'atanh', 'ceil', 'copysign', 'cos', 'cosh', 'degrees', 'e', 'erf', 'erfc', 'exp', 'expm1', 'fabs', 'factorial', 'floor', 'fmod', 'frexp', 'fsum', 'gamma', 'gcd', 'hypot', 'inf', 'isclose', 'isfinite', 'isinf', 'isnan', 'ldexp', 'lgamma', 'log', 'log10', 'log1p', 'log2', 'modf', 'nan', 'pi', 'pow', 'radians', 'remainder', 'sin', 'sinh', 'sqrt', 'tan', 'tanh', 'tau', 'trunc']


In [4]:
help(math)

Help on module math:

NAME
    math

MODULE REFERENCE
    https://docs.python.org/3.7/library/math
    
    The following documentation is automatically generated from the Python
    source files.  It may be incomplete, incorrect or include features that
    are considered implementation detail and may vary between Python
    implementations.  When in doubt, consult the module reference at the
    location listed above.

DESCRIPTION
    This module is always available.  It provides access to the
    mathematical functions defined by the C standard.

FUNCTIONS
    acos(x, /)
        Return the arc cosine (measured in radians) of x.
    
    acosh(x, /)
        Return the inverse hyperbolic cosine of x.
    
    asin(x, /)
        Return the arc sine (measured in radians) of x.
    
    asinh(x, /)
        Return the inverse hyperbolic sine of x.
    
    atan(x, /)
        Return the arc tangent (measured in radians) of x.
    
    atan2(y, x, /)
        Return the arc tangent (measured

In [7]:
print("π till 20 digits : {:.20}".format(math.pi))

π till 20 digits : 3.141592653589793116


In [8]:
math.log(32, 2)

5.0

In [9]:
math.log(10**5, 10)

5.0

In [10]:
import math as mt
mt.pi

3.141592653589793

In [16]:
## importing class and accessing the others 
import math
mx = math

In [14]:
mx.pi

3.141592653589793

In [15]:
## importing all the modules
from math import *
print(pi, sin(math.pi/2))

3.141592653589793 1.0


In [17]:
from math import *
from numpy import *
print(pi, log(32, 2))

TypeError: return arrays must be of ArrayType

What has happened? It worked before!

These kinds of "star imports" can occasionally lead to weird, difficult-to-debug situations.

The problem in this case is that the math and numpy modules both have functions called log, but they have different semantics. Because we import from numpy second, its log overwrites (or "shadows") the log variable we imported from math.

A good compromise is to import only the specific things we'll need from each module:

In [18]:
from math import log, pi
from numpy import asarray

### Sub modules

In [19]:
import numpy as np

In [22]:
## to access thesubmodule random
np.random.randint(0, 10, 23)

array([4, 9, 5, 6, 8, 8, 7, 7, 5, 6, 0, 3, 0, 9, 4, 1, 1, 4, 5, 0, 3, 0,
       8])

In [25]:
np.linspace(2,20,10)

array([ 2.,  4.,  6.,  8., 10., 12., 14., 16., 18., 20.])

In [26]:
rolls = np.random.randint(1,100, 10)

In [27]:
rolls

array([21, 29, 73, 81,  2, 91, 22, 12, 67, 82])

In [28]:
rolls+10

array([ 31,  39,  83,  91,  12, 101,  32,  22,  77,  92])

In [31]:
rolls > 3

array([ True,  True,  True,  True, False,  True,  True,  True,  True,
        True])

In [32]:
rolls <= 3

array([False, False, False, False,  True, False, False, False, False,
       False])

In [33]:
xlist = [[1,2,3], [4,5,6]]
x = np.asarray(xlist)

In [34]:
x[1, -1]

6

In [35]:
xlist[1, -1]

TypeError: list indices must be integers or slices, not tuple

In [36]:
xlist[1][-1]

6

numpy's ndarray type is specialized for working with multi-dimensional data, so it defines its own logic for indexing, allowing us to index by a tuple to specify the index at each dimension.

In [38]:
import tensorflow as tf
a = tf.constant(1)
b = tf.constant(2)
a+b

<tf.Tensor 'add_1:0' shape=() dtype=int32>

In [39]:
dir(list)

['__add__',
 '__class__',
 '__contains__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__imul__',
 '__init__',
 '__init_subclass__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__mul__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__reversed__',
 '__rmul__',
 '__setattr__',
 '__setitem__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 'append',
 'clear',
 'copy',
 'count',
 'extend',
 'index',
 'insert',
 'pop',
 'remove',
 'reverse',
 'sort']

In [41]:
list.__len__

<slot wrapper '__len__' of 'list' objects>

In [43]:
## "__add__" are oparator overloadings 
## programmer defines how a oparator should work in case of those methods were called
## like addition substraction etc.
[1,2,3].__contains__(5)

False