- Dynamic programing solved by
    * Dividing problem into subproblem.
    * then finding solution to subproblem and adding them up
    
> finding Longest increasing subsequence in a array 


In [72]:
import numpy as np
# my solution
# sequence is given arrange them in 2d array []
# find edges from element to element by given condition ->
# get maximum edged output


# DFS algorithm for vissiting the nodes
class DFS():
    
    def __init__(self, mat, v):
        self.G = mat
        self.V = v
        self.visit_vec = np.zeros((len(mat), len(mat)))
        self.count = {}
        self.c = 0;
        
    def _dfs(self, v):
        
        
        for w in self.G[v]:
            
            if self.visit_vec[v][w[1]] == 0:
                self.visit_vec[v][w[1]] = 1
                self.count[self.V][self.c] = w[1]
                self.c+=1
                self._dfs(w[1])
        
                
    def dfs(self, v):
        self.count[self.V] = {}
        self._dfs(v)
        return self.count

def visit(G, v):
    visit[v] = 1
    
def seq(A):
    # init the matrix with '0' initially to indicate the no edges
    M = np.zeros([len(A), len(A)])
    print(f"\n=>Matrix initialised : {M.shape}")
    
    M_map = [[] for i in range(len(A))]
    # check for each edge and update the related matrix
    for r in range(0, len(A)):
        M_map[r] = []
        for c in range(0, len(A)):
            if (A[r] <= A[c]) and (c >= r):
                M[r][c] = 1
                M_map[r].append([r, c])
    print(f"\nGraph matrix : \n{M}\n")
    print(f"\nCalculated the matrix : \n")
    new_map = {}
    for i in M_map:
        print(i)
        new_map[i[0][0]] = []
        for j in i:
            if len(j) == 2:
                new_map[j[0]].append(j[1])
            else:
                new_map[j[0]].append(j)
            
    print(f"\n{new_map}\n")
        
    # traversing over the nodes
    #count_nodes = []
    #for i in range(0, len(A)):
    #    d = DFS(M_map, i)
    #    count_nodes.append(d.dfs(i))
        
    #print(count_nodes)

In [73]:
seq([1,8,3,5,2,8,5,6,9])


=>Matrix initialised : (9, 9)

Graph matrix : 
[[1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [0. 1. 0. 0. 0. 1. 0. 0. 1.]
 [0. 0. 1. 1. 0. 1. 1. 1. 1.]
 [0. 0. 0. 1. 0. 1. 1. 1. 1.]
 [0. 0. 0. 0. 1. 1. 1. 1. 1.]
 [0. 0. 0. 0. 0. 1. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 1. 1. 1.]
 [0. 0. 0. 0. 0. 0. 0. 1. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1.]]


Calculated the matrix : 

[[0, 0], [0, 1], [0, 2], [0, 3], [0, 4], [0, 5], [0, 6], [0, 7], [0, 8]]
[[1, 1], [1, 5], [1, 8]]
[[2, 2], [2, 3], [2, 5], [2, 6], [2, 7], [2, 8]]
[[3, 3], [3, 5], [3, 6], [3, 7], [3, 8]]
[[4, 4], [4, 5], [4, 6], [4, 7], [4, 8]]
[[5, 5], [5, 8]]
[[6, 6], [6, 7], [6, 8]]
[[7, 7], [7, 8]]
[[8, 8]]

{0: [0, 1, 2, 3, 4, 5, 6, 7, 8], 1: [1, 5, 8], 2: [2, 3, 5, 6, 7, 8], 3: [3, 5, 6, 7, 8], 4: [4, 5, 6, 7, 8], 5: [5, 8], 6: [6, 7, 8], 7: [7, 8], 8: [8]}



In [38]:
x = [
    [12,34],
    [4],
    [7,8,9,1,2,3]
]
len(x)

3

In [45]:
x = []
x[0] = 1

IndexError: list assignment index out of range

In [61]:
x = {}
x[1] = 2

In [62]:
x

{1: 2}

In [63]:
if x[2]:
    print("H")

KeyError: 2